#!/bin/bash

set -e

do_ldconfig() {
	echo -e "/opt/e-sms/e_smi/lib/" > /etc/ld.so.conf.d/x86_64-libesmi_ib_lib.conf && ldconfig
}

case "$1" in
   configure)
       do_ldconfig
   ;;
   abort-upgrade|abort-remove|abort-deconfigure)
       echo "$1"
   ;;
   *)
       exit 0
   ;;
esac
